/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enroll;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class acad extends javax.swing.JFrame {

    /**
     * Creates new form acad
     */
    public acad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox8 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        hs_year = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        hs_roll = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        g_roll = new javax.swing.JTextField();
        i_roll = new javax.swing.JTextField();
        g_year = new javax.swing.JComboBox<>();
        i_year = new javax.swing.JComboBox<>();
        hs_board = new javax.swing.JComboBox<>();
        g_course = new javax.swing.JComboBox<>();
        i_board = new javax.swing.JComboBox<>();
        nxt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jComboBox8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~Select Year~", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", " " }));
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("STUDENT  ENROLLMENT  SYSTEM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 450, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("HIGH SCHOOL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 153, 194, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("INTERMEDIATE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 292, 581, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("GRADUATION");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 400, 144, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Roll No.");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 192, 194, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Year of Passing");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 192, 130, -1));

        hs_year.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        hs_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~Select Year~", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", " " }));
        hs_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hs_yearActionPerformed(evt);
            }
        });
        getContentPane().add(hs_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 220, 150, 29));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Board");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 192, 263, -1));
        getContentPane().add(hs_roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 219, 194, 29));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Board");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 325, 89, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Roll No.");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 433, 278, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Course");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 433, 267, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("Roll No.");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 325, 158, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("Year of Passing");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 433, 130, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setText("Year of Passing");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 325, 130, -1));

        g_roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g_rollActionPerformed(evt);
            }
        });
        getContentPane().add(g_roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 460, 194, 29));

        i_roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_rollActionPerformed(evt);
            }
        });
        getContentPane().add(i_roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 352, 194, 29));

        g_year.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        g_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~Select Year~", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", " " }));
        g_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g_yearActionPerformed(evt);
            }
        });
        getContentPane().add(g_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 461, 150, 29));

        i_year.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        i_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~Select Year~", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", " " }));
        i_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_yearActionPerformed(evt);
            }
        });
        getContentPane().add(i_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 353, 150, 29));

        hs_board.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        hs_board.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~Select ~", "State ", "CBSE ", "ICSE" }));
        getContentPane().add(hs_board, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 219, 263, 30));

        g_course.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        g_course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~Select ~", "BCA", "BBA", "BA", "BSc", "BCom", " " }));
        g_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g_courseActionPerformed(evt);
            }
        });
        getContentPane().add(g_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 460, 263, 30));

        i_board.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        i_board.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~Select ~", "State ", "CBSE ", "ISC" }));
        i_board.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_boardActionPerformed(evt);
            }
        });
        getContentPane().add(i_board, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 352, 263, 30));

        nxt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nxt.setText("SAVE");
        nxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxtActionPerformed(evt);
            }
        });
        getContentPane().add(nxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 528, 80, 40));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(958, 29, -1, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("STUDENT ID:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 25, -1, 34));

        sid.setBackground(new java.awt.Color(0, 51, 51));
        sid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sid.setForeground(new java.awt.Color(255, 255, 255));
        sid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidActionPerformed(evt);
            }
        });
        getContentPane().add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 65, 171, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(815, 530, 90, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enroll/Simple Backgrounds wallpaper 1920x1080.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void hs_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hs_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hs_yearActionPerformed

    private void i_rollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_rollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_rollActionPerformed

    private void g_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g_yearActionPerformed

    private void i_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_yearActionPerformed

    private void nxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxtActionPerformed
        // TODO add your handling code here:
         try{
            Class.forName("com.mysql.jdbc.Driver"); 
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/enroll_project","root",""); 
            String sql="insert into academic values (?,?,?,?,?,?,?,?,?,?)";
           
            PreparedStatement pst=con.prepareStatement(sql);
            
             pst.setString(1,sid.getText());
             pst.setString(2,hs_roll.getText());
             String hs;
             hs=hs_board.getSelectedItem().toString();
             pst.setString(3,hs);
             
             String hi;
             hi=hs_year.getSelectedItem().toString();
             pst.setString(4,hi);
             
             pst.setString(5,i_roll.getText());
             String inter;
             inter=i_board.getSelectedItem().toString();
             pst.setString(6,inter);
             
             String i;
             i=i_year.getSelectedItem().toString();
             pst.setString(7,i);
             
             pst.setString(8,g_roll.getText());
             String gra;
             gra=g_course.getSelectedItem().toString();
             pst.setString(9,gra);
             
             String g;
             g=g_year.getSelectedItem().toString();
             pst.setString(10,g);
             
             pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Saved!");
            
            con.close();
         }catch(Exception e)
         {
             JOptionPane.showMessageDialog(null,e);
         }
    }//GEN-LAST:event_nxtActionPerformed

    private void g_rollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g_rollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g_rollActionPerformed

    private void g_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g_courseActionPerformed

    private void i_boardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_boardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_boardActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                select_course select_courseFrame = new select_course();
                select_course.sid.setText(sid.getText());
                select_courseFrame.setVisible(true);
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          try{
            
            Class.forName("com.mysql.jdbc.Driver"); 
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/enroll_project","root",""); 
            String sql="update academic set hs_roll=?,hs_board=?,hs_year=?,i_roll=?,i_board=?,i_year=?,g_roll=?,g_course=?,g_year=? where sid=?";
            PreparedStatement pst=con.prepareStatement(sql);
            
            pst.setString(1,hs_roll.getText());
             String hs;
             hs=hs_board.getSelectedItem().toString();
             pst.setString(2,hs);
             
             String hi;
             hi=hs_year.getSelectedItem().toString();
             pst.setString(3,hi);
             
             pst.setString(4,i_roll.getText());
             String inter;
             inter=i_board.getSelectedItem().toString();
             pst.setString(5,inter);
             
             String i;
             i=i_year.getSelectedItem().toString();
             pst.setString(6,i);
             
             pst.setString(7,g_roll.getText());
             String gra;
             gra=g_course.getSelectedItem().toString();
             pst.setString(8,gra);
             
             String g;
             g=g_year.getSelectedItem().toString();
             pst.setString(9,g);
             
             pst.setString(10,sid.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated!");
            con.close();
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void sidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(acad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(acad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(acad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(acad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new acad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> g_course;
    private javax.swing.JTextField g_roll;
    private javax.swing.JComboBox<String> g_year;
    private javax.swing.JComboBox<String> hs_board;
    private javax.swing.JTextField hs_roll;
    private javax.swing.JComboBox<String> hs_year;
    private javax.swing.JComboBox<String> i_board;
    private javax.swing.JTextField i_roll;
    private javax.swing.JComboBox<String> i_year;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton nxt;
    public static javax.swing.JTextField sid;
    // End of variables declaration//GEN-END:variables
}
