/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enroll;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author mayan
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ad_name = new javax.swing.JTextField();
        ad_pwd = new javax.swing.JPasswordField();
        sub = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        spwd = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin Id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 129, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 117, -1));

        ad_name.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(ad_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 162, 220, 30));

        ad_pwd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(ad_pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 228, 220, 30));

        sub.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        sub.setText("SUBMIT");
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });
        getContentPane().add(sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("STUDENT  ENROLLMENT  SYSTEM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 450, -1));

        spwd.setForeground(new java.awt.Color(204, 204, 204));
        spwd.setText("show password");
        spwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spwdActionPerformed(evt);
            }
        });
        getContentPane().add(spwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 120, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enroll/reg1.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
        // TODO add your handling code here:
        if(ad_name.getText().equals("")&&(ad_pwd.getText().equals(""))){
            JOptionPane.showMessageDialog(null,"Please enter your Id and Password!");
        }
        else if(ad_name.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter Id");
        }
        else if(ad_pwd.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Please enter Password");
        }
        else{
        try{
            Class.forName("com.mysql.jdbc.Driver"); 
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/enroll_project","root",""); 
            String sql="select*from admin where ad_name=? and ad_pwd= ?";
            PreparedStatement pst=con.prepareStatement(sql);
            
            pst.setString(1,ad_name.getText());
            pst.setString(2,ad_pwd.getText());
            ResultSet rs=pst.executeQuery();
            if(rs.next()){
                view vFrame = new view();
                vFrame.setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Invalid Id or Password","Unsuccessful Login",JOptionPane.ERROR_MESSAGE);
            }  con.close();
                        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        }
                 
        ad_pwd.setText(null);        
        ad_name.setText(null);
        
    }//GEN-LAST:event_subActionPerformed

    private void spwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spwdActionPerformed
        // TODO add your handling code here:
        if(spwd.isSelected()){
            ad_pwd.setEchoChar((char)0);
        }
        else{
            ad_pwd.setEchoChar('*');
        }
    }//GEN-LAST:event_spwdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad_name;
    private javax.swing.JPasswordField ad_pwd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JCheckBox spwd;
    private javax.swing.JButton sub;
    // End of variables declaration//GEN-END:variables
}
