/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enroll;

import com.mysql.jdbc.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class details extends javax.swing.JFrame {

    /**
     * Creates new form details
     */
    public details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        view = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rectab = new javax.swing.JTable();
        upd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("STUDENT  ENROLLMENT  SYSTEM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 450, -1));

        view.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        view.setText("View Details");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        getContentPane().add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 370, 30));

        rectab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SID", "Enrollment_Number", "Student_name", "Course", "Semester", "E_Mail", "Phone_Number", "DOB", "Course_1", "Course_2", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rectab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rectabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(rectab);
        if (rectab.getColumnModel().getColumnCount() > 0) {
            rectab.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1200, -1));

        upd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        upd.setText("Update");
        upd.setBorder(null);
        upd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updActionPerformed(evt);
            }
        });
        getContentPane().add(upd, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 410, 30));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Home");
        jButton1.setPreferredSize(new java.awt.Dimension(320, 221));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 410, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enroll/reg1.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
        
        try{
            Class.forName("com.mysql.jdbc.Driver"); 
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/enroll_project","root",""); 
            String sql="select s_details.sid,s_details.student_name,s_details.e_mail,s_details.dob,s_details.address,course.semester,course.course_1,course.course_2,s_register.course,s_register.phone_number,verify.enrollment_number from course inner join s_details on s_details.sid=course.sid inner join s_register on s_register.e_mail=s_details.e_mail inner join verify on verify.sid=s_details.sid ";
            PreparedStatement pst=con.prepareStatement(sql);

            java.sql.ResultSet rs=pst.executeQuery();
            while(rs.next()){
                String id=String.valueOf(rs.getInt("sid"));
                String eid=String.valueOf(rs.getInt("enrollment_number"));
                String sn=rs.getString("student_name");
                String co=rs.getString("course");
                String sem=rs.getString("semester");
                String mail=rs.getString("e_mail");
                String ph=String.valueOf(rs.getInt("phone_number"));
                String dob=rs.getString("dob");
                String c1=rs.getString("course_1");
                String c2=rs.getString("course_2");
                String add=rs.getString("address");

                String tbData[]={id,eid,sn,co,sem,mail,ph,dob,c1,c2,add};
                DefaultTableModel tblModel=(DefaultTableModel)rectab.getModel();
                tblModel.addRow(tbData);
            }
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_viewActionPerformed

    private void updActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updActionPerformed
        // TODO add your handling code here:
        mainpage mpFrame = new mainpage();
        mpFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_updActionPerformed

    private void rectabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rectabMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rectabMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Student_enrollment Student_enrollmentFrame = new Student_enrollment();
        Student_enrollmentFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable rectab;
    private javax.swing.JButton upd;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
