/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enroll;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class next extends javax.swing.JFrame {

    /**
     * Creates new form next
     */
    public next() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        domi = new javax.swing.JTextField();
        in = new javax.swing.JTextField();
        high = new javax.swing.JTextField();
        gr = new javax.swing.JTextField();
        adhaar = new javax.swing.JButton();
        domicile = new javax.swing.JButton();
        hs = new javax.swing.JButton();
        inter = new javax.swing.JButton();
        grad = new javax.swing.JButton();
        photo = new javax.swing.JTextField();
        photo_browse = new javax.swing.JButton();
        unxt = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        adh = new javax.swing.JTextField();
        home = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("STUDENT  ENROLLMENT  SYSTEM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 31, 450, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Upload Your Documents Here-");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 127, 310, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Adhaar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 183, 208, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("High School Marksheet");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 293, 208, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Domicile");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 236, 208, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Graduation Marksheet");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 407, 208, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Intermediate Markseet");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 348, 208, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Photograph");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 466, 208, -1));

        sid.setBackground(new java.awt.Color(0, 51, 51));
        sid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sid.setForeground(new java.awt.Color(255, 255, 255));
        sid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidActionPerformed(evt);
            }
        });
        getContentPane().add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 54, 207, -1));

        domi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domiActionPerformed(evt);
            }
        });
        getContentPane().add(domi, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 236, 286, -1));
        getContentPane().add(in, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 348, 286, -1));
        getContentPane().add(high, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 290, 286, -1));

        gr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grActionPerformed(evt);
            }
        });
        getContentPane().add(gr, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 407, 286, -1));

        adhaar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        adhaar.setText("Upload");
        adhaar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adhaarActionPerformed(evt);
            }
        });
        getContentPane().add(adhaar, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 183, -1, -1));

        domicile.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        domicile.setText("Upload");
        domicile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domicileActionPerformed(evt);
            }
        });
        getContentPane().add(domicile, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 236, -1, -1));

        hs.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        hs.setText("Upload");
        hs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hsActionPerformed(evt);
            }
        });
        getContentPane().add(hs, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 290, -1, -1));

        inter.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        inter.setText("Upload");
        inter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interActionPerformed(evt);
            }
        });
        getContentPane().add(inter, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 348, -1, -1));

        grad.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        grad.setText("Upload");
        grad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradActionPerformed(evt);
            }
        });
        getContentPane().add(grad, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 407, -1, -1));
        getContentPane().add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 458, 286, -1));

        photo_browse.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        photo_browse.setText("Upload");
        photo_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photo_browseActionPerformed(evt);
            }
        });
        getContentPane().add(photo_browse, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 455, -1, 29));

        unxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        unxt.setText("SAVE");
        unxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unxtActionPerformed(evt);
            }
        });
        getContentPane().add(unxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 556, 117, 43));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("STUDENT ID:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 31, 159, -1));
        getContentPane().add(adh, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 183, 286, -1));

        home.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 556, 117, 43));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("GO TO NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 556, -1, 43));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enroll/Simple Backgrounds wallpaper 1920x1080.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 990, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grActionPerformed

    private void domiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_domiActionPerformed

    private void adhaarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adhaarActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser =new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename=f.getAbsolutePath();
        adh.setText(filename);
        

    }//GEN-LAST:event_adhaarActionPerformed

    private void domicileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domicileActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser =new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename=f.getAbsolutePath();
        domi.setText(filename);
    }//GEN-LAST:event_domicileActionPerformed

    private void hsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hsActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser =new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename=f.getAbsolutePath();
        high.setText(filename);
    }//GEN-LAST:event_hsActionPerformed

    private void interActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser =new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename=f.getAbsolutePath();
        in.setText(filename);
    }//GEN-LAST:event_interActionPerformed

    private void gradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser =new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename=f.getAbsolutePath();
        gr.setText(filename);
    }//GEN-LAST:event_gradActionPerformed

    private void photo_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photo_browseActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser =new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename=f.getAbsolutePath();
        photo.setText(filename);
    }//GEN-LAST:event_photo_browseActionPerformed

    private void unxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unxtActionPerformed
        // TODO add your handling code here:
        try{
            if(adh.getText().equals("")||(domi.getText().equals(""))||high.getText().equals("")||in.getText().equals("")||gr.getText().equals("")||photo.getText().equals("")){
               JOptionPane.showMessageDialog(null, "All the Documents are Mandatory to be Uploaded!","Upload Failure",JOptionPane.ERROR_MESSAGE);
               
            }
            else{
            Class.forName("com.mysql.jdbc.Driver"); 
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/enroll_project","root",""); 
            String sql="insert into documents values (?,?,?,?,?,?,?)";
            PreparedStatement pst=con.prepareStatement(sql); 
            pst.setString(1,sid.getText());
            pst.setString(2,adh.getText());
            pst.setString(3,domi.getText());
            pst.setString(4,high.getText());
            pst.setString(5,in.getText());
            pst.setString(6,gr.getText());
            pst.setString(7,photo.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Documents Uploaded!");
            
            con.close();
            }}catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_unxtActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
                Student_enrollment Student_enrollmentFrame = new Student_enrollment();
                Student_enrollmentFrame.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                verify verifyFrame = new verify();
                verifyFrame.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(next.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(next.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(next.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(next.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new next().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adh;
    private javax.swing.JButton adhaar;
    private javax.swing.JTextField domi;
    private javax.swing.JButton domicile;
    private javax.swing.JTextField gr;
    private javax.swing.JButton grad;
    private javax.swing.JTextField high;
    private javax.swing.JButton home;
    private javax.swing.JButton hs;
    private javax.swing.JTextField in;
    private javax.swing.JButton inter;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField photo;
    private javax.swing.JButton photo_browse;
    public static javax.swing.JTextField sid;
    private javax.swing.JButton unxt;
    // End of variables declaration//GEN-END:variables
}
