/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enroll;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class select_course extends javax.swing.JFrame {

    /**
     * Creates new form select_course
     */
    public select_course() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        semester = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        course_1 = new javax.swing.JComboBox<>();
        course_2 = new javax.swing.JComboBox<>();
        c3 = new javax.swing.JComboBox<>();
        c4 = new javax.swing.JComboBox<>();
        c5 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cnext = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        semester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Your  Semester", "1", "2", "3", "4" }));
        semester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterActionPerformed(evt);
            }
        });
        getContentPane().add(semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 186, 430, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("STUDENT  ENROLLMENT  SYSTEM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 28, 450, -1));

        course_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~Select Course 1~", "Fundamentals of Computers & Emerging Technologies", "Theory of Automata & Foraml Languages", "Artificial Intelligence", "Data Analytics" }));
        course_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course_1ActionPerformed(evt);
            }
        });
        getContentPane().add(course_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 248, 430, 30));

        course_2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~Select Course 2~", "Problem Solving Using C", "Object Oriented Programming", "Software Engineering", "Internet of Things" }));
        course_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course_2ActionPerformed(evt);
            }
        });
        getContentPane().add(course_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 312, 430, 30));

        c3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~Select Course 3~", "Principles of Management & Communication", "Operating Systems", "Computer Networks", "Big Data" }));
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        getContentPane().add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 376, 430, 30));

        c4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~Select Course 4~", "Discrete Mathematics", "Database Management Systems", "Cloud Computing", "Mobile Computing" }));
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });
        getContentPane().add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 434, 430, 30));

        c5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~Select Course 5~", "Computer Organization & Architecture", "Data Structures & Analysis of Algorithm" }));
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });
        getContentPane().add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 498, 430, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Select Your Courses According To Your Semester-");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 127, 440, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Semester:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 190, 80, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Course 1:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 252, 80, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Course 2:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 316, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Course 3:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 380, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Course 4:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 443, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Course 5:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 507, -1, -1));

        cnext.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cnext.setText("SAVE");
        cnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnextActionPerformed(evt);
            }
        });
        getContentPane().add(cnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 540, 90, 40));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("STUDENT ID:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 37, 97, -1));

        sid.setBackground(new java.awt.Color(0, 51, 51));
        sid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sid.setForeground(new java.awt.Color(255, 255, 255));
        sid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidActionPerformed(evt);
            }
        });
        getContentPane().add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 63, 194, 24));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 27, -1, 30));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 100, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enroll/Simple Backgrounds wallpaper 1920x1080.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c5ActionPerformed

    private void cnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnextActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver"); 
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/enroll_project","root",""); 
            String sql="insert into course values (?,?,?,?,?,?,?)";
           
            PreparedStatement pst=con.prepareStatement(sql);
                pst.setString(1,sid.getText());
             
             
             String seme;
             seme=semester.getSelectedItem().toString();
             pst.setString(2,seme);
             
             String c11;
            c11=course_1.getSelectedItem().toString();
            pst.setString(3,c11);
            
            String c22;
            c22=course_2.getSelectedItem().toString();
            pst.setString(4,c22);
            
            String c33;
            c33=c3.getSelectedItem().toString();
            pst.setString(5,c33);
            
            String c44;
            c44=c4.getSelectedItem().toString();
            pst.setString(6,c44);
            
            String c55;
            c55=c5.getSelectedItem().toString();
            pst.setString(7,c55);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Courses Added!");
            
            con.close();
     
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_cnextActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c4ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3ActionPerformed

    private void course_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course_2ActionPerformed

    private void course_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course_1ActionPerformed

    private void semesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semesterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                next nextFrame = new next();
                nextFrame.sid.setText(sid.getText());
                nextFrame.setVisible(true);
               
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            
            Class.forName("com.mysql.jdbc.Driver"); 
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/enroll_project","root",""); 
            String sql="update course set semester=?,course_1=?,course_2=?,c3=?,c4=?,c5=? where sid=?";
            PreparedStatement pst=con.prepareStatement(sql);
             String seme;
             seme=semester.getSelectedItem().toString();
             pst.setString(1,seme);
             
             String c11;
            c11=course_1.getSelectedItem().toString();
            pst.setString(2,c11);
            
            String c22;
            c22=course_2.getSelectedItem().toString();
            pst.setString(3,c22);
            
            String c33;
            c33=c3.getSelectedItem().toString();
            pst.setString(4,c33);
            
            String c44;
            c44=c4.getSelectedItem().toString();
            pst.setString(5,c44);
            
            String c55;
            c55=c5.getSelectedItem().toString();
            pst.setString(6,c55);
            
            pst.setString(7,sid.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated!");
            con.close();
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void sidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(select_course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(select_course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(select_course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(select_course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new select_course().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c3;
    private javax.swing.JComboBox<String> c4;
    private javax.swing.JComboBox<String> c5;
    private javax.swing.JButton cnext;
    private javax.swing.JComboBox<String> course_1;
    private javax.swing.JComboBox<String> course_2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> semester;
    public static javax.swing.JTextField sid;
    // End of variables declaration//GEN-END:variables
}
