/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enroll;

import static enroll.acad.sid;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class verify extends javax.swing.JFrame {

    /**
     * Creates new form verify
     */
    public verify() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        e_mail = new javax.swing.JTextField();
        vfy = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("STUDENT  ENROLLMENT  SYSTEM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 450, -1));

        e_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_mailActionPerformed(evt);
            }
        });
        getContentPane().add(e_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 260, 30));

        vfy.setBackground(new java.awt.Color(102, 0, 0));
        vfy.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        vfy.setForeground(new java.awt.Color(255, 255, 255));
        vfy.setText("VERIFY");
        vfy.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(255, 255, 51)));
        vfy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vfyActionPerformed(evt);
            }
        });
        getContentPane().add(vfy, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 610, 50));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("For Verification:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 210, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Student Id");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));
        getContentPane().add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 250, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("E-Mail Id");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 95, 24));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enroll/Simple Backgrounds wallpaper 1920x1080.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -240, 940, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void e_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_mailActionPerformed

    private void vfyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vfyActionPerformed
        // TODO add your handling code here:
        if(sid.getText().equals("")&&(e_mail.getText().equals(""))){
            JOptionPane.showMessageDialog(null,"Please enter Student Id and E-Mail Id!");
        }
        else if(e_mail.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter E-Mail Id!");
        }
        else if(sid.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Please enter Student Id!");
        }
        else{
        try{
            Class.forName("com.mysql.jdbc.Driver"); 
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/enroll_project","root",""); 
            String sql="select * from s_details where sid=? and e_mail= ?";
            PreparedStatement pst=con.prepareStatement(sql);
            
            pst.setString(1,sid.getText());
            pst.setString(2,e_mail.getText());
            ResultSet rs=pst.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null,"SUCCESS!");
                eno eFrame = new eno();
                eFrame.sid.setText(sid.getText());
                eFrame.setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Invalid E-Mail Id","Verification Failure",JOptionPane.ERROR_MESSAGE);
            }  con.close();
                        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        }
                 
        sid.setText(null);        
        e_mail.setText(null);
       
        
       
    }//GEN-LAST:event_vfyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(verify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(verify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(verify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(verify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new verify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField e_mail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JTextField sid;
    private javax.swing.JButton vfy;
    // End of variables declaration//GEN-END:variables
}
